### ISSUE TITLE
alttab behaves incorrectly when Control_R or Alt_R is used to initiate window switch

### ISSUE THREAD

**Issue by myelsukov** [sagb/alttab#97] opened 2020-04-08 17:58 UTC
I think the bug is here: https://github.com/sagb/alttab/blob/master/src/alttab.c#L521

The `if` thinks that modifier key is released so it closes the UI before exposing it.
The window is getting switched though.

**Comment by sagb** [comment] 2020-04-17 10:20
How can I reproduce? `alttab -mk Control_R` works fine for me.
`alttab -mk Alt_R` does not, because my window manager uses `Alt_R` for its purpose. Perhaps you have the problem for the same reason?

**Comment by myelsukov** [comment] 2020-04-17 15:59
1. Start `alttab -mk Control_L -w 1 -d 1 -s 1`
2. Now `Control_L+Tab` works as expected: a window with tiles is shown and you can switch between windows.
3. Try  `Control_R+Tab`. A window with tiles is **_not_** shown, but the focus is moved to the next window. If you keep pressing and releasing `Tab` without releasing `Control_R` or if you keep pressing and releasing `Control_R+Tab` the focus will be switched between the same two windows. 

May be this is a feature? :grin:

**Comment by sagb** [comment] 2020-04-19 19:10
I doubt it's alttab bug. The line you show is very core logic, I don't see any error here. Have you managed to change/fix the issue by changing this line?
What's your window manager?

**Comment by myelsukov** [comment] 2020-04-19 19:50
The logic is flawed. The `Alt/Mod1` modifier is triggered by the either `L_Alt` or `R_Alt` and it properly intercepted by the `alttab`.
Then in that line you check if the `L_Alt` is still pressed. Well it is not pressed, because I pressed `R_Alt` so you erroneously decide that `L_Alt` was released and remove the tiles window.

**Comment by sagb** [comment] 2020-04-19 20:13
Ah, I got it: you write about the comment "Alt released" in that line. It doesn't mean "Alt" literally, but any modifier set by `-mk`. Sorry for misleading comment.
Alttab *works* with various `-mk`, including `Control_R` and `Alt_R`.

If you want to try to resolve your issue, look at window manager key bindings, the question you ignored.

**Comment by myelsukov** [comment] 2020-04-19 22:05
I ignored question about WM as irrelevant :grin: 
If you are interested, then it's JWM and I personally control all keyboard bindings. Trust me, the keyboard binding has nothing to do with this problem.
The problem is the following:

When you bind the activation hotkey, you bind the keyboard modifier (Ctrl, Mod1, etc) independent on the position of the modifier key: left or right.
So, if you start `alttab` as `alttab -mk Control_L -w 1 -d 1 -s 1` you can trigger it with both Controls: Left and Right (try it if you don't trust me).
But the line https://github.com/sagb/alttab/blob/master/src/alttab.c#L521 tests for the specific control only. In our case it's Left Control.
So, if I trigger `alttab` with `Control_R` it gets triggered, the tiles window is displayed then it immediately disappears because that line :arrow_up:  thinks that Control_L key was released and removes the window. In fact, Control_L was never pressed.

**Comment by sagb** [comment] 2020-04-21 18:40
You are right, thank you for pointing out to this. Should be fixed now.

**Comment by myelsukov** [comment] 2020-04-21 18:59
I commented on the commit :grin:

**Comment by sagb** [comment] 2024-11-18 06:14
Summary:

If we were to fix this bug properly, we would need to rewrite event control from scratch, not to mention that I have little idea about the possible pitfalls;

and fixing this bug the way the original poster suggests is not elegant.

So let it remain a bug-feature forever...

**Closed by sagb** 2024-11-18 06:14 UTC
Labels: bug
